# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (2a9aaffe-c2e6-4cdd-ae1e-69763ee7c082)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az login --service-principal --username $(USERNAME) --password $(PASSWORD) --tenant $(TENANT)'
    useGlobalConfig: true
    
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: ls
  displayName: 'List'
- script: az config set extension.use_dynamic_install=yes_without_prompt
  displayName: 'Allow extensions'
- script: echo $(System.AccessToken) | az devops login --organization https://dev.azure.com/ymadrigal2/
  displayName: 'Login to DevOps'




- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (2a9aaffe-c2e6-4cdd-ae1e-69763ee7c082)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './script.sh'
    useGlobalConfig: true