# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: ls
  displayName: 'List'
- script: az config set extension.use_dynamic_install=yes_without_prompt
  displayName: 'Allow extensions'
- script: echo $(System.AccessToken) | az devops login
  displayName: 'Login to DevOps'


# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Azure subscription 1 (2a9aaffe-c2e6-4cdd-ae1e-69763ee7c082)'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az login --service-principal --username 5f5f9336-dfce-46cc-8acd-81e6eb9c8a8e --password bie8Q~vS2h9JsgbZbmFKoTOsqcXInf_xND2BIaTj --tenant f524efae-c921-4e8b-851e-b002089d974d'
#     useGlobalConfig: true

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (2a9aaffe-c2e6-4cdd-ae1e-69763ee7c082)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './script.sh'
    useGlobalConfig: true