trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    mkdir test
    cd test 
  displayName: 'Create folder test'

- script: |
    ls
    pwd
  displayName: 'Listar y mostrar ruta'
